# 将来的には対応する規約の読込
inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込
require:
  - rubocop-rails

AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.6
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    # - !ruby/regexp /old_and_unused\.rb$/
    - 'node_modules/node-sass/src/libsass/contrib/libsass.spec'
    - '/Users/glaciermelt/environment/keikoba_app/node_modules/node-sass/src/libsass/extconf.rb'
    - 'node_modules/node-sass/src/libsass/extconf.rb'

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

##################### Style ##################################

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# !! のイディオムを許可
Style/DoubleNegation:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# selfが無くても良い時に省略するか。model内において、ローカル変数とメソッド呼び出しの区別をつけた方が分かりやすい場合が多い
Style/RedundantSelf:
  Enabled: false

##################### Lint ##################################

##################### Metrics ##################################

# 変数の代入(A)、メソッドの呼び出し等(B)、条件分岐(C)から算出される複雑度
Metrics/AbcSize:
  Max: 30

# 循環的複雑度 ≒ 分岐の数
Metrics/CyclomaticComplexity:
  Max: 10

# 1行の文字数
Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

# メソッドの行数
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

# RSpec のコードだけ Metrics/BlockLength を無視する
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'