version: '3'
services:
  db:
    image: mysql:5.6.51
    platform: linux/x86_64
    ports:
      - "4306:3306"
    env_file: db.env

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/keikoba_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: db.env
